Weekly update (2024-03-07)
opentofu/opentofu pull request #1348
Opened 2024-03-07 15:36 UTC by janosdebugs

Weekly update!

2024-03-07 15:42 UTC, cube2222 approved these changes

2024-03-07 16:18 UTC, Yantrio requested changes

2024-03-07 16:18 UTC, Yantrio commented on WEEKLY_UPDATES.md
> +Hello there! This week we got state encryption running on the main branch the first time, and we are planning to release an alpha build next week with a passphrase key provider and possible AWS KMS i
```suggestion
Hello there! This week we got state encryption running on the main branch for the first time, and we are planning to release an alpha build next week with a passphrase key provider and possibly the AWS KMS integration.
```

2024-03-07 17:16 UTC, cam72cam submitted a review, later dismissed

2024-03-08 09:54 UTC, Yantrio approved these changes

2024-03-08 09:54 UTC, merged