RFC - Add Exclude Flag for Targeted Plan/Apply
opentofu/opentofu pull request #1717
Opened 2024-06-11 15:39 UTC by JamesBalazs

Resolves # 

## Target Release

1.8.0

## Checklist

- [ ] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [ ] I have not used an AI coding assistant to create this PR.
- [ ] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.

### Go checklist

 

- [ ] I have run golangci-lint on my change and receive no errors relevant to my code.
- [ ] I have run existing tests to ensure my code doesn't break anything.
- [ ] I have added tests for all relevant use cases of my code, and those tests are passing.
- [ ] I have only exported functions, variables and structs that should be used from other packages.
- [ ] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

2024-06-12 10:18 UTC, ollevche requested changes
Thank you for the RFC!

2024-06-12 10:18 UTC, ollevche commented on rfc/20240611-ExcludeFlag.md
> +`opentf plan -exclude module.something_broken` / `opentf apply -exclude module.something_broken` should be added to --help output for plan/apply.
```suggestion
`tofu plan -exclude module.something_broken` / `tofu apply -exclude module.something_broken` should be added to --help output for plan/apply.
```

2024-06-12 10:18 UTC, ollevche commented on rfc/20240611-ExcludeFlag.md
> +- If both targets and excludes are provided, use the most specific path eg:
I believe we should postpone this use case (target + exclude). We could also add it later if requested by the community. See https://github.com/opentofu/opentofu/issues/426#issuecomment-2137356757

2024-06-16 14:20 UTC, RLRabinowitz reviewed
Thank you very much for your contribution and involvement @JamesBalazs  🙏🏻 
Much appreciated

2024-06-16 14:20 UTC, RLRabinowitz commented on rfc/20240611-ExcludeFlag.md
> +## Proposed Solution
This section is missing the specifics of how the `-exclude` flag will work. For example - what happens to dependencies and dependents of an excluded resource, what happens when there's a mixture of `-target` and `-exclude` flag in the same execution (should not be allowed for now)

For example - following up on [this comment](https://github.com/opentofu/opentofu/issues/426#issuecomment-2137148391) from the issue

2024-06-16 14:20 UTC, RLRabinowitz commented on rfc/20240611-ExcludeFlag.md
> +- `TargetsTransformer.Transform` should remove vertices that are in (or children of items in) `t.Excludes` if `t.Excludes` are provided (just like it currently removes vertices that _aren't_ in `t.Ta
```suggestion
- `TargetsTransformer.Transform` should remove vertices that are in `t.Excludes`, or descendants of items in `t.Excludes`, if `t.Excludes` are provided (just like it currently removes vertices that _aren't_ in `t.Targets`).
```

2024-06-16 14:20 UTC, RLRabinowitz commented on rfc/20240611-ExcludeFlag.md
> +- When destroying, if there are dependencies of an excluded resource, the dependencies should also be kept (excluded from change)
I feel like this statement should be clarified. When destroying, the dependencies are the ones excluded, and not the dependent nodes. This, however, is talking about the non-inverted graph, not to be confused with the inverted graph of the destroy action.

2024-06-16 14:20 UTC, RLRabinowitz commented on rfc/20240611-ExcludeFlag.md
> +Potential limitations or impacts on other areas of the codebase: backends are imported from TFE which we can't change. We discussed in the issue that there could be some incompatibility, depending ho
This technically means that remote backends or clouds would not get the `-exclude` flag arguments in remote runs triggered from a local machine

2024-06-16 15:48 UTC, cam72cam commented
@JamesBalazs it looks like you missed the DCO Signoff on your latest commit.  You can amend that commit with the `-s` flag.

2024-07-25 13:41 UTC, RLRabinowitz commented
Hey @JamesBalazs , thank you very much for your work with the RFC and on the issue!

I've created an RFC detailing how an `-exclude` flag should behave in https://github.com/opentofu/opentofu/pull/1860

Would love to hear your thoughts 🙏🏻

2024-07-26 11:45 UTC, closed without merging